// <auto-generated />
namespace triluatsoft.tls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update20180827AddColumnIsDeleted_tblTimeSheet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update20180827AddColumnIsDeleted_tblTimeSheet));
        
        string IMigrationMetadata.Id
        {
            get { return "201808270215478_update20180827AddColumnIsDeleted_tblTimeSheet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
