// <auto-generated />
namespace triluatsoft.tls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtable_ACT_CommissionPayments_CommissionPolicies_CustomerOfficers_Commissions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtable_ACT_CommissionPayments_CommissionPolicies_CustomerOfficers_Commissions));
        
        string IMigrationMetadata.Id
        {
            get { return "201808280928490_addtable_ACT_CommissionPayments_CommissionPolicies_CustomerOfficers_Commissions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
