// <auto-generated />
namespace triluatsoft.tls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_claimtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_claimtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201804140717098_add_claimtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
